import { useState } from 'react'
import type { RepoAnalysis } from '../types'
import SummaryCard from './SummaryCard'
import TechStackBadge from './TechStackBadge'
import FileTree from './FileTree'
import MermaidRenderer from './MermaidRenderer'
import StatsGrid from './StatsGrid'
import ChatTab from './ChatTab'
import CodeHealthGauge from './CodeHealthGauge'
import LanguageBar from './LanguageBar'
import RepoCatalog from './RepoCatalog'

interface AnalysisDashboardProps {
  analysis: RepoAnalysis
  messages: { role: 'user' | 'assistant'; content: string; timestamp: string }[]
  isStreaming: boolean
  onChatSend: (message: string) => void
  onChatClear: () => void
}

const RepoIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" style={{ color: 'var(--accent)' }}>
    <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z" />
  </svg>
)

const CopyIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
  </svg>
)

const ShareIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="18" cy="5" r="3" />
    <circle cx="6" cy="12" r="3" />
    <circle cx="18" cy="19" r="3" />
    <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
    <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
  </svg>
)

const CheckIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="20 6 9 17 4 12" />
  </svg>
)

export default function AnalysisDashboard({
  analysis,
  messages,
  isStreaming,
  onChatSend,
  onChatClear,
}: AnalysisDashboardProps) {
  const [toast, setToast] = useState<string | null>(null)
  const [copiedState, setCopiedState] = useState<'markdown' | 'share' | null>(null)

  const showToast = (msg: string) => {
    setToast(msg)
    setTimeout(() => setToast(null), 3000)
  }

  const copyToClipboard = async (text: string): Promise<boolean> => {
    if (navigator.clipboard) {
      try {
        await navigator.clipboard.writeText(text)
        return true
      } catch {
        // Fall back below
      }
    }
    try {
      const textArea = document.createElement('textarea')
      textArea.value = text
      textArea.style.position = 'fixed'
      textArea.style.top = '0'
      textArea.style.left = '0'
      textArea.style.width = '2em'
      textArea.style.height = '2em'
      textArea.style.padding = '0'
      textArea.style.border = 'none'
      textArea.style.outline = 'none'
      textArea.style.boxShadow = 'none'
      textArea.style.background = 'transparent'
      document.body.appendChild(textArea)
      textArea.focus()
      textArea.select()
      textArea.setSelectionRange(0, textArea.value.length)
      const success = document.execCommand('copy')
      document.body.removeChild(textArea)
      return success
    } catch {
      return false
    }
  }

  const handleCopyMarkdown = async () => {
    const repoName = (analysis.repoUrl || '').replace('https://github.com/', '') || analysis.name
    const markdown = `# ${repoName} — Analysis Report

## Summary & Purpose
${analysis.summary?.purpose || 'N/A'}

## Key Architecture & Design
${analysis.summary?.architecture || 'N/A'}

## Code Quality & Health Assessment
${analysis.summary?.quality || 'N/A'}

## Tech Stack Overview
${(analysis.techStack || []).map(t => `- **${t.name}**: ${t.category}`).join('\n')}

---
*Generated by GitGrok AI GitHub Analyzer on ${new Date().toLocaleDateString()}*`

    const ok = await copyToClipboard(markdown)
    if (ok) {
      setCopiedState('markdown')
      showToast('Copied README Markdown report to clipboard!')
      setTimeout(() => setCopiedState(null), 2500)
    } else {
      showToast('Could not copy report. Please copy manually.')
    }
  }

  const handleShareLink = async () => {
    const repoPath = (analysis.repoUrl || '').replace(/^https?:\/\/(www\.)?github\.com\//, '')
    const shareUrl = `${window.location.origin}${window.location.pathname}?repo=${encodeURIComponent(repoPath)}&branch=${encodeURIComponent(analysis.branch || 'main')}`
    
    const ok = await copyToClipboard(shareUrl)
    if (ok) {
      setCopiedState('share')
      showToast('Shareable analysis link copied to clipboard!')
      setTimeout(() => setCopiedState(null), 2500)
    } else {
      showToast('Could not copy link. Please copy URL manually.')
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, position: 'relative' }}>
      {/* Toast Notification */}
      {toast && (
        <div className="animate-fade-in" style={{
          position: 'fixed',
          bottom: 28,
          right: 28,
          zIndex: 9999,
          background: 'var(--text-heading, #0f172a)',
          color: '#ffffff',
          padding: '12px 20px',
          borderRadius: 14,
          fontSize: 13,
          fontWeight: 600,
          boxShadow: '0 10px 30px rgba(0,0,0,0.15)',
          display: 'flex',
          alignItems: 'center',
          gap: 10,
        }}>
          <span style={{ width: 8, height: 8, borderRadius: '50%', background: '#10b981' }} />
          {toast}
        </div>
      )}

      {/* Header Banner */}
      <div className="animate-fade-in-up stagger-1">
        <div className="surface" style={{ padding: '18px 20px', display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <div style={{
            width: 40,
            height: 40,
            borderRadius: 12,
            background: 'var(--accent-soft)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            flexShrink: 0,
          }}>
            <RepoIcon />
          </div>
          <div style={{ flex: 1, minWidth: 200 }}>
            <h2 style={{
              fontFamily: 'var(--font-heading)',
              fontSize: 16,
              fontWeight: 700,
              color: 'var(--text-heading)',
              letterSpacing: '-0.02em',
              lineHeight: 1.2,
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap',
            }}>
              {(analysis.repoUrl || '').replace('https://github.com/', '')}
            </h2>
            <p style={{
              fontSize: 12,
              color: 'var(--text-secondary)',
              fontFamily: 'var(--font-mono)',
            }}>
              Analyzed {analysis.analyzedAt ? new Date(analysis.analyzedAt).toLocaleString() : 'N/A'} · branch "{analysis.branch}"
            </p>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            <button
              onClick={handleCopyMarkdown}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 6,
                padding: '7px 14px',
                borderRadius: 9999,
                border: copiedState === 'markdown' ? '1px solid rgba(22, 163, 74, 0.4)' : '1px solid var(--border)',
                background: copiedState === 'markdown' ? 'rgba(22, 163, 74, 0.12)' : 'var(--bg-tertiary, #fcfbf9)',
                color: copiedState === 'markdown' ? '#15803d' : 'var(--text-heading)',
                fontSize: 12,
                fontWeight: 600,
                cursor: 'pointer',
                transition: 'all 0.15s ease',
              }}
            >
              {copiedState === 'markdown' ? (
                <>
                  <CheckIcon />
                  Copied Markdown!
                </>
              ) : (
                <>
                  <CopyIcon />
                  Copy Markdown
                </>
              )}
            </button>

            <button
              onClick={handleShareLink}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 6,
                padding: '7px 14px',
                borderRadius: 9999,
                border: copiedState === 'share' ? '1px solid rgba(22, 163, 74, 0.4)' : '1px solid var(--border)',
                background: copiedState === 'share' ? 'rgba(22, 163, 74, 0.12)' : 'var(--bg-tertiary, #fcfbf9)',
                color: copiedState === 'share' ? '#15803d' : 'var(--text-heading)',
                fontSize: 12,
                fontWeight: 600,
                cursor: 'pointer',
                transition: 'all 0.15s ease',
              }}
            >
              {copiedState === 'share' ? (
                <>
                  <CheckIcon />
                  Link Copied!
                </>
              ) : (
                <>
                  <ShareIcon />
                  Share Link
                </>
              )}
            </button>

            <span style={{
              fontSize: 11,
              fontFamily: 'var(--font-mono)',
              color: 'var(--success)',
              background: 'rgba(22, 163, 74, 0.08)',
              border: '1px solid rgba(22, 163, 74, 0.15)',
              padding: '4px 10px',
              borderRadius: 9999,
              fontWeight: 700,
            }}>Analyzed</span>
          </div>
        </div>
      </div>

      <StatsGrid stats={analysis.stats} />

      {/* Language Breakdown */}
      <LanguageBar fileTree={analysis.fileTree} />

      {/* Licensing & Entry Point Catalog */}
      <RepoCatalog
        fileTree={analysis.fileTree}
        techStack={analysis.techStack}
        license={analysis.stats?.license}
        branch={analysis.branch}
        repoUrl={analysis.repoUrl}
      />

      <div className="animate-fade-in-up stagger-2">
        <CodeHealthGauge analysis={analysis} />
      </div>

      <SummaryCard summary={analysis.summary} />

      <div className="animate-fade-in-up stagger-3" style={{ marginTop: 4 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
          <div style={{ width: 3, height: 16, borderRadius: 2, background: 'var(--accent)' }} />
          <h3 className="section-label">Tech Stack</h3>
        </div>
        <TechStackBadge items={analysis.techStack} />
      </div>

      <div style={{ marginTop: 4 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
          <div style={{ width: 3, height: 16, borderRadius: 2, background: 'var(--accent)' }} />
          <h3 className="section-label">Architecture Diagram</h3>
        </div>
        <MermaidRenderer
          diagram={analysis.archDiagram}
          fileTree={analysis.fileTree}
          techStack={analysis.techStack}
          repoName={analysis.name}
        />
      </div>

      <div style={{
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: 20,
        marginTop: 4,
      }}>
        <FileTree nodes={analysis.fileTree} />
        <ChatTab
          messages={messages}
          isStreaming={isStreaming}
          onSend={onChatSend}
          onClear={onChatClear}
        />
      </div>
    </div>
  )
}

